apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-c
        image: tonyq2k3/mern-stack-frontend:dev
        imagePullPolicy: Always
        env:
          - name: REACT_APP_API
            value: "http://gateway-service:8000"
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
        ports:
        - containerPort: 3000