name: Frontend CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main"]

    
jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=NT114-DevOps_mern-stack-frontend
            -Dsonar.organization=nt114-devops

  Build:
    needs: Analysis
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x,  21.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Build run
      run: npm run build --if-present
      env:
        CI: ""

    - name: Test run
      run: npm test -- --watchAll=false
      env:
        CI: ""
  

  Build-image:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: tonyq2k3/mern-stack-frontend:dev
