name: Production environment deployment

on:
    workflow_dispatch:
        inputs:
          tag:
            description: 'Docker tag to update manifest'
            required: true
            type: string

jobs:
    Build-image:
        runs-on: ubuntu-latest
        steps:
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and push
                uses: docker/build-push-action@v5
                with:
                    push: true
                    tags: tonyq2k3/mern-stack-frontend:${{ github.sha }}
        
    Update-manifest:
        runs-on: ubuntu-latest
        needs: Build-image
        if: ${{ success() }}
        steps:
            -
                name: Checkout infrastructure repo
                uses: actions/checkout@v3
                with:
                    repository: NT114-DevOps/infrastructures
                    ref: 'main'
                    token: ${{ secrets.GIT_TOKEN }}
            -
                name: Update frontend manifest
                run: |
                    git config --global user.email "ntbquoc2015@gmail.com"
                    git config --global user.name "TonyQ2k3"
                    echo "Update frontend version to ${{ github.event.inputs.tag }}"
                    sed -i 's#tonyq2k3/mern-stack-frontend:[^[:space:]]*$#tonyq2k3/mern-stack-frontend:${{ github.event.inputs.tag }}#g' ./production/frontend/frontend-deploy.yaml
                    git add ./production/frontend/frontend-deploy.yaml
                    git commit -m "Update frontend version to ${{ github.event.inputs.tag }} in production environment"
                    git push origin main
