name: Frontend CD

on:
  push:
    branches: [ "main" ]

env:
  EKS_CLUSTER_NAME: microservice-cluster
  AWS_REGION: us-east-1

jobs:
    deploy-eks:
        runs-on: ubuntu-latest
        steps:
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
              aws-region: ${{env.AWS_REGION}}
    
          - name: Update kube config
            run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
    
          - name: Deploy to EKS
            run: kubectl apply -f https://raw.githubusercontent.com/NT114-DevOps/mern-stack-frontend/main/kubernetes/frontend-deploy.yaml



            # git clone https://github.com/NT114-DevOps/mern-stack-frontend.git
            # cd mern-stack-frontend
            # kubectl apply -f kubernetes/frontend-deploy.yaml