name: Frontend CD

on:
  workflow_run:
    workflows: ["Frontend CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: sudo docker pull tonyq2k3/mern-stack-frontend:dev
      - name: Delete old Docker container
        run: sudo docker rm -f backend-container || true
      - name: Run a new container
        run: sudo docker run -d -p 3000:3000 --name frontend-container tonyq2k3/mern-stack-frontend:dev
